services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - mongodbdata:/data/db

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata: